spring.application.name=product-crud
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/cruddb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt secret generate using: openssl rand -base64 32
jwt.secret=I+37+X9WCjq5wi9pBxiNV6jKg1n7HzKxbi1JQKqmpdg=
# 24 hours in second
jwt.expiration=86400