spring.application.name=product-crud
spring.config.import = file:.env[.properties]
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt secret generate using: openssl rand -base64 32
jwt.secret=${JWT_SECRET}
# 24 hours in second
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-token=${REFRESH_TOKEN_EXPIRATION}

# Google OAuth2 Registration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Scopes (using index-based notation for lists)
spring.security.oauth2.client.registration.google.scope[0]=email
spring.security.oauth2.client.registration.google.scope[1]=profile

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache type
spring.cache.type=redis

# minio
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME}

#set max and min size to file upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB