spring.application.name=product-crud
spring.config.import = file:.env[.properties]
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt secret generate using: openssl rand -base64 32
jwt.secret=${JWT_SECRET}
# 24 hours in second
jwt.expiration=${JWT_EXPIRATION}

# Google OAuth2 Registration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Scopes (using index-based notation for lists)
spring.security.oauth2.client.registration.google.scope[0]=email
spring.security.oauth2.client.registration.google.scope[1]=profile