package com.example.productcrud.constraint;

public enum ErrorCode {
    SUCCESS,
    REQUIRED_FIELD_MISSING,
    INVALID_FIELD_FORMAT,
    PRODUCT_NOT_FOUND,
    DUPLICATE_PRODUCT_CODE,
    PRODUCT_ALREADY_INACTIVE,
    INVALID_PRODUCT_STATUS_CHANGE,
    PRODUCT_HAS_ACTIVE_ORDERS,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_INACTIVE,
    INVALID_CURRENCY_FORMAT,
    TOKEN_EXPIRED,
    ACCESS_DENIED
}
